services:
  android-emulator:
    image: budtmo/docker-android:latest
    privileged: true
    environment:
      - EMULATOR_DEVICE="Samsung Galaxy S10"
      - WEB_VNC=true
      - APPIUM=true
    ports:
      - "6080:6080"  # VNC
      - "4723:4723"  # Appium
      - "5555:5555"  # ADB (TCP)
    devices:
      - /dev/kvm:/dev/kvm
    networks:
      - android-network
    entrypoint: >
      bash -c "
        emulator -avd '${EMULATOR_DEVICE}' -no-audio -no-window -gpu off &
        adb wait-for-device &&
        adb tcpip 5555 &&
        tail -f /dev/null
      "

  test-runner:
    image: ababko/appium-python:latest
    environment:
      - ADB_DEVICE=${ADB_DEVICE}
    volumes:
      - ./app:/app
      - ./reports:/app/reports
    depends_on:
      - android-emulator
    networks:
      - android-network
    entrypoint: /app/entrypoint.sh

networks:
  android-network:
    driver: bridge
