services:
  android-emulator:
    image: budtmo/docker-android:latest
    privileged: true
    environment:
      - EMULATOR_DEVICE="samsung_galaxy_s10_13.0"
      - WEB_VNC=true
      - APPIUM=true
    ports:
      - "6080:6080"  # VNC
      - "4723:4723"  # Appium
      - "5555:5555"  # ADB (TCP)
    devices:
      - /dev/kvm:/dev/kvm
    networks:
      - android-network
    entrypoint: >
      bash -c "
        # Create AVD (if not already created)
        if [ ! -d /home/runner/.android/avd/samsung_galaxy_s10_13.0.avd ]; then
          echo 'Creating AVD for Samsung Galaxy S10...'
          echo no | avdmanager create avd -n samsung_galaxy_s10_13.0 -k 'system-images;android-30;google_apis;x86_64'
        fi
        # Start the emulator
        emulator -avd samsung_galaxy_s10_13.0 -no-audio -no-window -gpu off &
        adb wait-for-device &&
        adb tcpip 5555 &&
        tail -f /dev/null
      "

  test-runner:
    image: ababko/appium-python:latest
    environment:
      - ADB_DEVICE=${ADB_DEVICE}
    volumes:
      - ./app:/app
      - ./reports:/app/reports
    depends_on:
      - android-emulator
    networks:
      - android-network
    entrypoint: /app/entrypoint.sh

networks:
  android-network:
    driver: bridge
