services:
  android-emulator:
    image: budtmo/docker-android:latest
    privileged: true
    environment:
      - EMULATOR_DEVICE="samsung_galaxy_s10_13.0"
      - WEB_VNC=true
      - APPIUM=true
    ports:
      - "6080:6080"  # VNC
      - "4723:4723"  # Appium
      - "5555:5555"  # ADB (TCP)
    devices:
      - /dev/kvm:/dev/kvm
    volumes:
      - ./android-avd:/home/androidusr/.android/avd  # Map to the correct AVD directory
    networks:
      - android-network
    entrypoint: >
      bash -c "
        # Create AVD (if not already created)
        if [ ! -d /home/androidusr/.android/avd/samsung_galaxy_s10_13.0.avd ]; then
          echo 'Creating AVD for Samsung Galaxy S10...'
          avdmanager create avd -n samsung_galaxy_s10_13.0 -k 'system-images;android-33;google_apis;x86_64' -d 'Samsung Galaxy S10'
        fi
        # Start the emulator in the background
        emulator -avd samsung_galaxy_s10_13.0 -no-audio -no-window -gpu off &
        
        # Wait for emulator to fully start
        echo 'Waiting for emulator to start...'
        adb wait-for-device &&

        # Set ADB to TCP mode on port 5555
        adb tcpip 5555 &&

        # Tail to keep container running
        tail -f /dev/null
      "

  test-runner:
    image: ababko/appium-python:latest
    environment:
      - ADB_DEVICE=${ADB_DEVICE}
    volumes:
      - ./app:/app
      - ./reports:/app/reports
    depends_on:
      - android-emulator
    networks:
      - android-network
    entrypoint: /app/entrypoint.sh

networks:
  android-network:
    driver: bridge
