version: '3.8'
services:
  android-emulator:
    image: budtmo/docker-android:latest
    privileged: true
    environment:
      - EMULATOR_DEVICE="Samsung Galaxy S10"
      - WEB_VNC=true
      - APPIUM=true
    ports:
      - "6080:6080"
      - "4723:4723"
      - "5555:5555"
    networks:
      - android-network

  test-runner:
    image: ababko/appium-python:latest
    environment:
      - ADB_DEVICE=${ADB_DEVICE}
    volumes:
      - ./app:/app
      - ./reports:/app/reports
    depends_on:
      - android-emulator
    networks:
      - android-network
    entrypoint: /app/entrypoint.sh

networks:
  android-network:
    driver: bridge
