services:
  android-emulator:
    image: budtmo/docker-android:latest
    privileged: true
    environment:
      - EMULATOR_DEVICE="Samsung Galaxy S10"
      - WEB_VNC=true
      - APPIUM=true
    ports:
      - "6080:6080"  # VNC
      - "4723:4723"  # Appium
      - "5555:5555"  # ADB (TCP)
    devices:
      - /dev/kvm:/dev/kvm
    volumes:
      - ./android-avd:/home/androidusr/.android/avd  # Map to the correct AVD directory
    networks:
      - android-network
    entrypoint: >
      bash -c "
        # Check if the AVD exists, create if not
        if [ ! -d /home/androidusr/.android/avd/samsung_galaxy_s10_13.0.avd ]; then
          echo 'Creating AVD for Samsung Galaxy S10...'
          avdmanager create avd -f -n samsung_galaxy_s10_13.0 -k 'system-images;android-33;google_apis;x86_64' -d 'Samsung Galaxy S10' -p /home/androidusr/.android/avd || { echo 'Failed to create AVD'; exit 1; }
        else
          echo 'AVD already exists.'
        fi

        # Start the emulator
        echo 'Starting the emulator...'
        emulator -avd samsung_galaxy_s10_13.0 -no-audio -no-window -gpu off &
        
        # Wait for the emulator to fully boot (give it time)
        adb wait-for-device || { echo 'Failed to connect to device'; exit 1; }
        adb tcpip 5555 || { echo 'Failed to set ADB to TCP mode'; exit 1; }

        # Ensure emulator is running before proceeding
        echo 'Emulator started, ready for tests...'
        tail -f /dev/null
      "

  test-runner:
    image: ababko/appium-python:latest
    environment:
      - ADB_DEVICE=${ADB_DEVICE}
    volumes:
      - ./app:/app
      - ./reports:/app/reports
    depends_on:
      - android-emulator
    networks:
      - android-network
    entrypoint: /app/entrypoint.sh

networks:
  android-network:
    driver: bridge
