name: Mobile App Tests with Allure Report

on: [workflow_dispatch]

jobs:
  android-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Set the ADB_DEVICE for GitHub Actions
      - name: Set ADB_DEVICE for GitHub Actions
        run: |
          echo "ADB_DEVICE=android-emulator:5555" >> $GITHUB_ENV

      # Set up Docker Compose
      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      # Pull your custom Docker image
      - name: Pull Custom Docker Image
        run: docker pull ababko/appium-python:latest

      # Pull the budtmo/docker-android image
      - name: Pull Android Emulator Image
        run: docker pull budtmo/docker-android:latest

      # Start Docker Compose
      - name: Start Docker Compose
        run: |
          docker-compose up -d  # Start the containers in detached mode
          sleep 10  # Wait for the containers to initialize (you can adjust the sleep time as needed)

      # Run tests using the Appium container
      - name: Run Tests with Appium
        run: |
          docker-compose exec appium-tests pytest --alluredir=/app/reports/allure-results

      # Clean up Docker Compose services
      - name: Clean up Docker Compose
        run: docker-compose down
