name: Run Mobile Tests

on: [workflow_dispatch]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    services:
      emulator:
        image: budtmo/docker-android:emulator_11.0
        ports:
          - 4723:4723
          - 6080:6080
        options: >
          --device=/dev/kvm
        env:
          EMULATOR_DEVICE: "Samsung Galaxy S10"
          APPIUM: "true"

    steps:
      # Checkout the code (if entrypoint.sh is in the repo)
      - name: Checkout code
        uses: actions/checkout@v3

      # Ensure entrypoint.sh is executable
      - name: Ensure entrypoint.sh is executable
        run: chmod +x app/entrypoint.sh

      # Check emulator and Appium server status
      - name: Check Emulator and Appium Status
        run: |
          curl --fail http://localhost:4723/status || exit 1
          adb devices

      # Run Mobile Tests
      - name: Run Mobile Tests
        uses: addnab/docker-run-action@v3
        with:
          image: ababko/appium-python:latest
          options: >
            --network host
            -e ADB_DEVICE=emulator:5555
          run: /app/entrypoint.sh

      # Dump logs in case of failure
      - name: Dump logs on failure
        if: failure()
        run: |
          mkdir -p logs
          docker logs emulator > logs/docker.log

      # Upload logs as artifacts for debugging
      - name: Upload logs as artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: container-logs
          path: logs/

      # Cleanup Docker resources
      - name: Cleanup Docker Resources
        if: always()
        run: docker system prune -f
