name: Mobile App Tests with Allure Report

on: [workflow_dispatch]

jobs:
  android-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Pull your custom Docker image
      - name: Pull Custom Docker Image
        run: docker pull ababko/appium-python:latest

      # Pull the budtmo/docker-android image
      - name: Pull Android Emulator Image
        run: docker pull budtmo/docker-android:latest

      # Start emulator container
      - name: Start Android Emulator
        run: |
          docker run -d --name android-container \
            -p 6080:6080 -p 4723:4723 \
            -e EMULATOR_DEVICE="Samsung Galaxy S10" \
            -e WEB_VNC=true \
            -e APPIUM=true \
            budtmo/docker-android:latest

      # Start test container and run tests
      - name: Run Tests
        run: |
          docker run --rm --network host \
            -v $(pwd)/reports:/app/reports \
            ababko/appium-python pytest --alluredir=reports/allure-results
